import Foundation
import SwiftSyntax
import SwiftParser

/// Parses a .swiftinterface file and extracts public API declarations
/// for bridge code generation.
struct BridgeGenerator {

    struct ExtractedType {
        let name: String
        let kind: String // "struct", "class", "enum"
        var initializers: [ExtractedInit] = []
        var methods: [ExtractedMethod] = []
        var properties: [ExtractedProperty] = []
        var staticMethods: [ExtractedMethod] = []
        var staticProperties: [ExtractedProperty] = []
    }

    struct ExtractedInit {
        let parameters: [ExtractedParam]
    }

    struct ExtractedMethod {
        let name: String
        let parameters: [ExtractedParam]
        let returnType: String?
        let isAsync: Bool
        let isThrowing: Bool
        let isMutating: Bool
    }

    struct ExtractedProperty {
        let name: String
        let type: String
        let hasSetter: Bool
    }

    struct ExtractedParam {
        let label: String?
        let name: String
        let type: String
        let hasDefault: Bool
    }

    /// Parse a .swiftinterface file and extract public API declarations.
    static func parse(interfaceFile: String) -> [ExtractedType] {
        guard let source = try? String(contentsOfFile: interfaceFile, encoding: .utf8) else {
            print("Error: Cannot read file \(interfaceFile)")
            return []
        }
        let sourceFile = Parser.parse(source: source)
        let extractor = APIExtractor()
        extractor.walk(sourceFile)
        return extractor.types
    }

    /// Filter extracted types through an allowlist.
    static func filter(types: [ExtractedType], allowlist: [String: [String]?]) -> [ExtractedType] {
        types.compactMap { type in
            guard let allowedMethods = allowlist[type.name] else { return nil }
            var filtered = type
            if let methods = allowedMethods {
                filtered.methods = type.methods.filter { methods.contains($0.name) }
                filtered.properties = type.properties.filter { methods.contains($0.name) }
                filtered.staticMethods = type.staticMethods.filter { methods.contains($0.name) }
                filtered.staticProperties = type.staticProperties.filter { methods.contains($0.name) }
            }
            return filtered
        }
    }

    /// Generate Swift source code for bridge registration.
    static func generateRegistration(types: [ExtractedType], frameworkName: String) -> String {
        var lines: [String] = []
        lines.append("// Auto-generated bridge registration for \(frameworkName)")
        lines.append("// Generated by lantern-bridge-gen")
        lines.append("")
        lines.append("import Foundation")
        lines.append("import LanternVM")
        lines.append("import LanternBridge")
        lines.append("import \(frameworkName)")
        lines.append("")
        lines.append("public func register\(frameworkName)Bridge(on registry: BridgeRegistry) {")

        for type in types {
            lines.append("")
            lines.append("    // MARK: - \(type.name)")
            lines.append("")

            // Constructor
            if !type.initializers.isEmpty {
                let initInfo = type.initializers[0]
                let paramLabels = initInfo.parameters.map { p in
                    p.label.map { "\"\($0)\"" } ?? "nil"
                }.joined(separator: ", ")
                lines.append("    registry.registerType(\"\(type.name)\") { args in")
                lines.append("        // TODO: Convert args and call \(type.name)(...)")
                lines.append("        .nil_")
                lines.append("    }")
            }

            // Properties
            for prop in type.properties {
                lines.append("    registry.registerProperty(typeName: \"\(type.name)\", name: \"\(prop.name)\",")
                lines.append("        getter: { receiver in")
                lines.append("            // TODO: Extract \(prop.name) from \(type.name)")
                lines.append("            .nil_")
                lines.append("        },")
                if prop.hasSetter {
                    lines.append("        setter: { receiver, value in")
                    lines.append("            // TODO: Set \(prop.name) on \(type.name)")
                    lines.append("        }")
                } else {
                    lines.append("        setter: nil")
                }
                lines.append("    )")
            }

            // Methods
            for method in type.methods {
                let paramStr = method.parameters.map { "\($0.label ?? $0.name): \($0.type)" }.joined(separator: ", ")
                lines.append("    registry.registerMethod(typeName: \"\(type.name)\", selector: \"\(method.name)\", parameterLabels: []) { receiver, args in")
                lines.append("        // \(method.name)(\(paramStr))\(method.returnType.map { " -> \($0)" } ?? "")")
                lines.append("        // TODO: Extract receiver, convert args, call method")
                lines.append("        .nil_")
                lines.append("    }")
            }

            // Static methods
            for method in type.staticMethods {
                lines.append("    registry.registerStaticMethod(typeName: \"\(type.name)\", selector: \"\(method.name)\", parameterLabels: []) { args in")
                lines.append("        // TODO: Call \(type.name).\(method.name)(...)")
                lines.append("        .nil_")
                lines.append("    }")
            }
        }

        lines.append("}")
        return lines.joined(separator: "\n")
    }
}

// MARK: - SwiftSyntax API Extractor

private class APIExtractor: SyntaxVisitor {
    var types: [BridgeGenerator.ExtractedType] = []
    private var currentType: BridgeGenerator.ExtractedType?

    init() {
        super.init(viewMode: .sourceAccurate)
    }

    override func visit(_ node: StructDeclSyntax) -> SyntaxVisitorContinueKind {
        let name = node.name.trimmedDescription
        if hasPublicModifier(node.modifiers) {
            currentType = BridgeGenerator.ExtractedType(name: name, kind: "struct")
        }
        return .visitChildren
    }

    override func visitPost(_ node: StructDeclSyntax) {
        if let type = currentType {
            types.append(type)
            currentType = nil
        }
    }

    override func visit(_ node: ClassDeclSyntax) -> SyntaxVisitorContinueKind {
        let name = node.name.trimmedDescription
        if hasPublicModifier(node.modifiers) {
            currentType = BridgeGenerator.ExtractedType(name: name, kind: "class")
        }
        return .visitChildren
    }

    override func visitPost(_ node: ClassDeclSyntax) {
        if let type = currentType {
            types.append(type)
            currentType = nil
        }
    }

    override func visit(_ node: EnumDeclSyntax) -> SyntaxVisitorContinueKind {
        let name = node.name.trimmedDescription
        if hasPublicModifier(node.modifiers) {
            currentType = BridgeGenerator.ExtractedType(name: name, kind: "enum")
        }
        return .visitChildren
    }

    override func visitPost(_ node: EnumDeclSyntax) {
        if let type = currentType {
            types.append(type)
            currentType = nil
        }
    }

    override func visit(_ node: InitializerDeclSyntax) -> SyntaxVisitorContinueKind {
        guard currentType != nil, hasPublicModifier(node.modifiers) else { return .skipChildren }
        let params = extractParameters(node.signature.parameterClause.parameters)
        currentType?.initializers.append(BridgeGenerator.ExtractedInit(parameters: params))
        return .skipChildren
    }

    override func visit(_ node: FunctionDeclSyntax) -> SyntaxVisitorContinueKind {
        guard currentType != nil, hasPublicModifier(node.modifiers) else { return .skipChildren }
        let name = node.name.trimmedDescription
        let params = extractParameters(node.signature.parameterClause.parameters)
        let returnType = node.signature.returnClause?.type.trimmedDescription
        let isAsync = node.signature.effectSpecifiers?.asyncSpecifier != nil
        let isThrowing = node.signature.effectSpecifiers?.throwsClause != nil
        let isStatic = node.modifiers.contains { $0.name.tokenKind == .keyword(.static) || $0.name.tokenKind == .keyword(.class) }
        let isMutating = node.modifiers.contains { $0.name.tokenKind == .keyword(.mutating) }

        let method = BridgeGenerator.ExtractedMethod(
            name: name,
            parameters: params,
            returnType: returnType,
            isAsync: isAsync,
            isThrowing: isThrowing,
            isMutating: isMutating
        )

        if isStatic {
            currentType?.staticMethods.append(method)
        } else {
            currentType?.methods.append(method)
        }
        return .skipChildren
    }

    override func visit(_ node: VariableDeclSyntax) -> SyntaxVisitorContinueKind {
        guard currentType != nil, hasPublicModifier(node.modifiers) else { return .skipChildren }
        let isStatic = node.modifiers.contains { $0.name.tokenKind == .keyword(.static) }

        for binding in node.bindings {
            let name = binding.pattern.trimmedDescription
            let type = binding.typeAnnotation?.type.trimmedDescription ?? "Any"
            var hasSetter = node.bindingSpecifier.tokenKind == .keyword(.var)

            // Check accessor block for get-only
            if let accessorBlock = binding.accessorBlock {
                if case .accessors(let accessors) = accessorBlock.accessors {
                    hasSetter = accessors.contains { $0.accessorSpecifier.tokenKind == .keyword(.set) }
                }
            }

            let prop = BridgeGenerator.ExtractedProperty(name: name, type: type, hasSetter: hasSetter)
            if isStatic {
                currentType?.staticProperties.append(prop)
            } else {
                currentType?.properties.append(prop)
            }
        }
        return .skipChildren
    }

    // MARK: - Helpers

    private func hasPublicModifier(_ modifiers: DeclModifierListSyntax) -> Bool {
        modifiers.contains { $0.name.tokenKind == .keyword(.public) || $0.name.tokenKind == .keyword(.open) }
    }

    private func extractParameters(_ params: FunctionParameterListSyntax) -> [BridgeGenerator.ExtractedParam] {
        params.map { param in
            let label = param.firstName.tokenKind == .wildcard ? nil : param.firstName.trimmedDescription
            let name = param.secondName?.trimmedDescription ?? param.firstName.trimmedDescription
            let type = param.type.trimmedDescription
            let hasDefault = param.defaultValue != nil
            return BridgeGenerator.ExtractedParam(label: label, name: name, type: type, hasDefault: hasDefault)
        }
    }
}
