import LanternVM
import LanternCompiler
import LanternDebugger
import LanternBridge
#if canImport(SwiftUI)
import SwiftUI
import LanternSwiftUI
#endif

/// The main entry point for the Lantern interpreter.
/// Compiles and executes Swift source, manages the bridge registry,
/// and exposes the debugger.
public final class Interpreter {
    private let vm: VM
    private let compiler: BytecodeCompiler
    private let _debugger: Debugger

    /// The bridge registry for registering host types and functions.
    public let bridge: BridgeRegistry

    /// The debugger interface. Always available — debugging is always on.
    public var debugger: DebuggerInterface { _debugger }

    /// The output handler for print() and debugPrint() calls.
    public var outputHandler: OutputHandler = StandardOutputHandler()

    /// Maximum call stack depth before stack overflow error.
    public var maxCallDepth: Int = 1024

    /// Maximum execution steps before timeout. Nil means no limit.
    public var maxExecutionSteps: Int? = nil

    /// Create an interpreter with an optional bridge registry.
    public init(bridge: BridgeRegistry = .default) {
        self.bridge = bridge
        self.vm = VM(maxCallDepth: 1024)
        self.compiler = BytecodeCompiler()
        self._debugger = Debugger(vm: vm, compiler: compiler)
        registerBuiltins()
        #if canImport(SwiftUI)
        registerSwiftUIBridge(on: bridge, vm: vm)
        #if canImport(Charts)
        registerChartsBridge(on: bridge, vm: vm)
        #endif
        #if canImport(MapKit)
        registerMapKitBridge(on: bridge, vm: vm)
        #endif
        #endif
        registerBridgeTypesAsGlobals()
        // Tell the compiler about bridge type names so they aren't treated as self.property
        compiler.externalGlobals = Set(bridge.registeredTypes)
        // Tell the compiler about static members for implicit member resolution (.title → Font.title)
        var staticMembers: Set<String> = []
        for typeName in bridge.registeredTypes {
            for propName in bridge.registeredStaticProperties(forType: typeName) {
                staticMembers.insert("\(typeName).\(propName)")
            }
        }
        compiler.externalStaticMembers = staticMembers
        // Wire bridge dispatch into VM for runtime method/property lookup
        vm.bridgeMethodLookup = { [weak bridge] typeName, selector in
            bridge?.lookupMethod(typeName: typeName, selector: selector)
        }
        vm.bridgePropertyLookup = { [weak bridge] typeName, name in
            bridge?.lookupProperty(typeName: typeName, name: name)?.getter
        }
        // Wire @Published property change notifications
        #if canImport(SwiftUI)
        vm.publishedPropertyHandler = { [weak self] instanceRef, propertyName in
            // Find any ObservableWrapper watching this instance and notify it
            if let wrapper = self?.observableWrappers[ObjectIdentifier(instanceRef)] {
                wrapper.propertyDidChange(propertyName)
            }
        }
        #endif
    }

    #if canImport(SwiftUI)
    /// Tracks active LanternObservableWrapper instances by their wrapped InstanceRef identity.
    private var observableWrappers: [ObjectIdentifier: LanternObservableWrapper] = [:]

    /// @AppStorage property-to-UserDefaults-key mappings per type.
    /// Populated by the compiler's appStorageProperties dict.
    public var appStorageMappings: [String: [String: String]] = [:] // [typeName: [propName: udKey]]

    /// Persistent state stores for view instances, keyed by InstanceRef identity.
    /// Keeps the store alive across SwiftUI view recreations.
    private var stateStores: [ObjectIdentifier: LanternStateStore] = [:]

    /// Create an ObservableObject wrapper for an interpreted class instance.
    /// Use this when passing an interpreted class as @ObservedObject to a view.
    public func wrapObservable(_ instance: InstanceRef) -> LanternObservableWrapper {
        let id = ObjectIdentifier(instance)
        if let existing = observableWrappers[id] { return existing }
        let wrapper = LanternObservableWrapper(vm: vm, instance: instance)
        observableWrappers[id] = wrapper
        return wrapper
    }
    #endif

    /// Copy bridge-registered type constructors and methods into the VM environment
    /// so the compiler-generated bytecode can find them as global functions.
    private func registerBridgeTypesAsGlobals() {
        for typeName in bridge.registeredTypes {
            // Register constructor as a global function (e.g., Text(...))
            if let constructor = bridge.lookupConstructor(typeName) {
                let fn = NativeFunctionRef(name: typeName, arity: -1) { args in
                    try constructor(args)
                }
                vm.environment.setGlobal(typeName, value: .nativeFunction(fn))
            }

            // Register methods as "TypeName.methodName" globals for bridge dispatch
            for methodName in bridge.registeredMethods(forType: typeName) {
                if let method = bridge.lookupMethod(typeName: typeName, selector: methodName) {
                    let qualifiedName = "\(typeName).\(methodName)"
                    let fn = NativeFunctionRef(name: qualifiedName, arity: -1) { args in
                        guard let receiver = args.first else { return .nil_ }
                        let methodArgs = Array(args.dropFirst())
                        return try method(receiver, methodArgs)
                    }
                    vm.environment.setGlobal(qualifiedName, value: .nativeFunction(fn))
                }
            }

            // Register static properties as "TypeName.propertyName" globals (e.g. Font.title)
            for propName in bridge.registeredStaticProperties(forType: typeName) {
                if let prop = bridge.lookupStaticProperty(typeName: typeName, name: propName) {
                    let qualifiedName = "\(typeName).\(propName)"
                    if let value = try? prop.getter() {
                        vm.environment.setGlobal(qualifiedName, value: value)
                    }
                }
            }
        }

    }

    /// Register built-in functions (print, etc.) in the VM environment.
    private func registerBuiltins() {
        // print — variadic, joins with space, appends newline
        let printFn = NativeFunctionRef(name: "print", arity: -1) { [weak self] args in
            let text = args.map { val -> String in
                // Check for CustomStringConvertible (description computed property)
                if case .instance(let ref) = val {
                    let getterName = "\(ref.typeName).__get_description"
                    if let getter = self?.vm.environment.getGlobal(getterName),
                       let result = try? self?.vm.invokeValue(getter, args: [val]) {
                        return result.description
                    }
                }
                return val.description
            }.joined(separator: " ")
            self?.outputHandler.handlePrint(text + "\n")
            self?.vm.delegate?.vm(self!.vm, didProduceOutput: text + "\n")
            return .void
        }
        vm.environment.setGlobal("print", value: .nativeFunction(printFn))

        // debugPrint
        let debugPrintFn = NativeFunctionRef(name: "debugPrint", arity: -1) { [weak self] args in
            let text = args.map { $0.debugSummary }.joined(separator: " ")
            self?.outputHandler.handleDebugPrint(text + "\n")
            return .void
        }
        vm.environment.setGlobal("debugPrint", value: .nativeFunction(debugPrintFn))

        // String() — convert value to string
        let stringFn = NativeFunctionRef(name: "String", arity: 1) { args in
            guard let arg = args.first else { return .string("") }
            switch arg {
            case .string(let s): return .string(s)
            case .int(let i): return .string(String(i))
            case .double(let d): return .string(String(d))
            case .bool(let b): return .string(String(b))
            case .array(let arr):
                // String(["h","e","l","l","o"]) → "hello" (for reversed strings etc.)
                let chars = arr.compactMap { $0.stringValue }
                if chars.count == arr.count { return .string(chars.joined()) }
                return .string(arg.description)
            default: return .string(arg.description)
            }
        }
        vm.environment.setGlobal("String", value: .nativeFunction(stringFn))

        // Int() — convert value to int
        let intFn = NativeFunctionRef(name: "Int", arity: 1) { args in
            guard let arg = args.first else { return .nil_ }
            switch arg {
            case .int(let i): return .int(i)
            case .double(let d): return .int(Int(d))
            case .string(let s): return s.isEmpty ? .nil_ : (Int(s).map { .int($0) } ?? .nil_)
            default: return .nil_
            }
        }
        vm.environment.setGlobal("Int", value: .nativeFunction(intFn))

        // Double() — convert value to double
        let doubleFn = NativeFunctionRef(name: "Double", arity: 1) { args in
            guard let arg = args.first else { return .nil_ }
            switch arg {
            case .double(let d): return .double(d)
            case .int(let i): return .double(Double(i))
            case .string(let s): return Double(s).map { .double($0) } ?? .nil_
            default: return .nil_
            }
        }
        vm.environment.setGlobal("Double", value: .nativeFunction(doubleFn))

        // abs()
        let absFn = NativeFunctionRef(name: "abs", arity: 1) { args in
            guard let arg = args.first else { return .nil_ }
            switch arg {
            case .int(let i): return .int(abs(i))
            case .double(let d): return .double(abs(d))
            default: return arg
            }
        }
        vm.environment.setGlobal("abs", value: .nativeFunction(absFn))

        // min/max
        let minFn = NativeFunctionRef(name: "min", arity: -1) { args in
            guard args.count >= 2 else { return args.first ?? .nil_ }
            if let a = args[0].intValue, let b = args[1].intValue { return .int(Swift.min(a, b)) }
            if let a = args[0].doubleValue, let b = args[1].doubleValue { return .double(Swift.min(a, b)) }
            return args[0]
        }
        vm.environment.setGlobal("min", value: .nativeFunction(minFn))

        let maxFn = NativeFunctionRef(name: "max", arity: -1) { args in
            guard args.count >= 2 else { return args.first ?? .nil_ }
            if let a = args[0].intValue, let b = args[1].intValue { return .int(Swift.max(a, b)) }
            if let a = args[0].doubleValue, let b = args[1].doubleValue { return .double(Swift.max(a, b)) }
            return args[0]
        }
        vm.environment.setGlobal("max", value: .nativeFunction(maxFn))

        // Array() — convert to array or Array(repeating:count:)
        let arrayFn = NativeFunctionRef(name: "Array", arity: -1) { args in
            if args.count == 2 {
                // Array(repeating: value, count: n)
                let value = args[0]
                if let count = args[1].intValue {
                    return .array(Swift.Array(repeating: value, count: count))
                }
            }
            guard let arg = args.first else { return .array([]) }
            if case .array(let a) = arg { return .array(a) }
            if case .string(let s) = arg { return .array(s.map { .string(String($0)) }) }
            return .array([arg])
        }
        vm.environment.setGlobal("Array", value: .nativeFunction(arrayFn))

        // type(of:) — return type name
        let typeOfFn = NativeFunctionRef(name: "type", arity: 1) { args in
            guard let arg = args.first else { return .string("Void") }
            return .string(arg.typeName)
        }
        vm.environment.setGlobal("type", value: .nativeFunction(typeOfFn))

        // zip()
        let zipFn = NativeFunctionRef(name: "zip", arity: 2) { args in
            guard case .array(let a) = args[0], case .array(let b) = args[1] else { return .array([]) }
            let count = Swift.min(a.count, b.count)
            var result: [Value] = []
            for i in 0..<count { result.append(.array([a[i], b[i]])) }
            return .array(result)
        }
        vm.environment.setGlobal("zip", value: .nativeFunction(zipFn))

        // Operator functions as values (for reduce(0, +) etc.)
        let addOpFn = NativeFunctionRef(name: "+", arity: 2) { args in
            let a = args[0], b = args[1]
            if let la = a.intValue, let lb = b.intValue { return .int(la + lb) }
            if let la = a.doubleValue, let lb = b.doubleValue { return .double(la + lb) }
            if case .string(let la) = a, case .string(let lb) = b { return .string(la + lb) }
            return .nil_
        }
        vm.environment.setGlobal("+", value: .nativeFunction(addOpFn))

        let mulOpFn = NativeFunctionRef(name: "*", arity: 2) { args in
            if let a = args[0].intValue, let b = args[1].intValue { return .int(a * b) }
            if let a = args[0].doubleValue, let b = args[1].doubleValue { return .double(a * b) }
            return .nil_
        }
        vm.environment.setGlobal("*", value: .nativeFunction(mulOpFn))

        // Result type constructors
        let successFn = NativeFunctionRef(name: "Result.success", arity: 1) { args in
            return .enumCase(EnumCaseRef(typeName: "Result", caseName: "success", associatedValues: args))
        }
        vm.environment.setGlobal("Result.success", value: .nativeFunction(successFn))

        let failureFn = NativeFunctionRef(name: "Result.failure", arity: 1) { args in
            return .enumCase(EnumCaseRef(typeName: "Result", caseName: "failure", associatedValues: args))
        }
        vm.environment.setGlobal("Result.failure", value: .nativeFunction(failureFn))

        // Static methods: Int.random(in:), Double.random(in:), Bool.random()
        let intRandomFn = NativeFunctionRef(name: "Int.random", arity: 1) { args in
            guard case .range(let lo, let hi, let inclusive) = args.first else { return .nil_ }
            let upper = inclusive ? hi : hi - 1
            guard lo <= upper else { return .nil_ }
            return .int(Int.random(in: lo...upper))
        }
        vm.environment.setGlobal("Int.random", value: .nativeFunction(intRandomFn))

        let doubleRandomFn = NativeFunctionRef(name: "Double.random", arity: 1) { args in
            guard case .range(let lo, let hi, _) = args.first else { return .nil_ }
            return .double(Double.random(in: Double(lo)...Double(hi)))
        }
        vm.environment.setGlobal("Double.random", value: .nativeFunction(doubleRandomFn))

        let boolRandomFn = NativeFunctionRef(name: "Bool.random", arity: 0) { _ in
            return .bool(Bool.random())
        }
        vm.environment.setGlobal("Bool.random", value: .nativeFunction(boolRandomFn))

        // Numeric type constants
        vm.environment.setGlobal("Int.min", value: .int(Int.min))
        vm.environment.setGlobal("Int.max", value: .int(Int.max))
        vm.environment.setGlobal("Double.pi", value: .double(Double.pi))
        vm.environment.setGlobal("Double.infinity", value: .double(Double.infinity))
        vm.environment.setGlobal("Double.nan", value: .double(Double.nan))
    }

    /// Compile Swift source into a compiled program.
    public func compile(
        source: String,
        fileName: String = "<input>"
    ) -> Result<CompiledProgram, CompilerDiagnostics> {
        compiler.compile(source: source, fileName: fileName)
    }

    /// Compile and execute Swift source in one step.
    @discardableResult
    public func run(
        source: String,
        fileName: String = "<input>"
    ) -> Result<Value, InterpreterError> {
        switch compile(source: source, fileName: fileName) {
        case .success(let program):
            return execute(program: program)
        case .failure(let diags):
            let msg = diags.diagnostics.map { (d: CompilerDiagnostic) -> String in d.description }.joined(separator: "\n")
            return .failure(InterpreterError(kind: .custom("compilation"), message: msg))
        }
    }

    /// Execute a previously compiled program.
    @discardableResult
    public func execute(program: CompiledProgram) -> Result<Value, InterpreterError> {
        _debugger.load(program)
        registerBuiltins()
        registerEnumCases(from: program)
        if let limit = maxExecutionSteps { vm.executionLimit = limit }
        vm.run()

        switch vm.state {
        case .halted:
            let result = vm.stackSnapshot.last ?? .void
            return .success(wrapViewInstanceIfNeeded(result))
        case .error(let err):
            return .failure(err)
        default:
            return .success(.void)
        }
    }

    /// Execute a program, pausing at the first executable statement.
    @discardableResult
    public func executePaused(program: CompiledProgram) -> Result<Value, InterpreterError> {
        _debugger.load(program)
        registerBuiltins()
        registerEnumCases(from: program)
        if let limit = maxExecutionSteps { vm.executionLimit = limit }
        _debugger.startPaused()

        switch vm.state {
        case .halted:
            return .success(wrapViewInstanceIfNeeded(vm.stackSnapshot.last ?? .void))
        case .error(let err):
            return .failure(err)
        case .paused:
            return .success(.void) // Paused at first statement — expected
        default:
            return .success(.void)
        }
    }

    /// Execute a single expression and return its value.
    public func evaluate(
        expression: String,
        fileName: String = "<expr>"
    ) -> Result<Value, InterpreterError> {
        run(source: expression, fileName: fileName)
    }

    /// Register enum case values as globals from the compiled program's type table.
    private func registerEnumCases(from program: CompiledProgram) {
        for typeInfo in program.typeTable where typeInfo.kind == .enum {
            // Determine raw value type from conformances
            let hasIntRaw = typeInfo.conformances.contains("Int")
            let hasStringRaw = typeInfo.conformances.contains("String")

            for (i, prop) in typeInfo.properties.enumerated() {
                let qualifiedName = "\(typeInfo.name).\(prop.name)"
                var rawValue: Value? = nil
                if hasIntRaw {
                    // Auto-assign int raw values starting from 0
                    rawValue = .int(i)
                } else if hasStringRaw {
                    // String raw value = case name
                    rawValue = .string(prop.name)
                }
                // Check if typeAnnotation carries an explicit raw value
                if let annotation = prop.typeAnnotation, let intVal = Int(annotation) {
                    rawValue = .int(intVal)
                } else if let annotation = prop.typeAnnotation, annotation.hasPrefix("\"") {
                    rawValue = .string(String(annotation.dropFirst().dropLast()))
                }
                // Check if this case has associated values (indicated by isComputed flag)
                if prop.isComputed {
                    // Register as a constructor function
                    let tName = typeInfo.name
                    let cName = prop.name
                    let rVal = rawValue
                    let constructorFn = NativeFunctionRef(name: qualifiedName, arity: -1) { args in
                        return .enumCase(EnumCaseRef(typeName: tName, caseName: cName, associatedValues: args, rawValue: rVal))
                    }
                    vm.environment.setGlobal(qualifiedName, value: .nativeFunction(constructorFn))
                } else {
                    let caseRef = EnumCaseRef(typeName: typeInfo.name, caseName: prop.name, rawValue: rawValue)
                    vm.environment.setGlobal(qualifiedName, value: .enumCase(caseRef))
                }
            }
        }
    }

    /// Reset interpreter state, clearing all globals and history.
    /// Bridge registrations are preserved.
    public func reset() {
        vm.load(CompiledProgram())
    }

    // MARK: - SwiftUI Support

    /// If the value is an instance of a View-conforming type, wrap it in a ViewBox
    /// so the preview system can render it. Otherwise return the value unchanged.
    /// Public so LanternKit can wrap values from the debugger (e.g. lastExpressionResult).
    public func wrapViewInstanceIfNeeded(_ value: Value) -> Value {
        #if canImport(SwiftUI)
        guard case .instance(let ref) = value else { return value }
        // Check if this type conforms to View
        guard let typeInfo = vm.currentProgram?.typeTable.first(where: { $0.name == ref.typeName }),
              typeInfo.conformances.contains("View") else { return value }
        // Wrap in a ViewStub → ViewBox so PreviewCanvasView renders it live
        let stub = makeView(from: ref)
        return .hostObject(HostObjectRef(object: ViewBox(AnyView(stub)), typeName: ref.typeName))
        #else
        return value
        #endif
    }

    /// Create an instance of a view type defined in the last compiled program.
    public func createInstance(typeName: String, arguments: [Value] = []) -> InstanceRef? {
        // Try to find a constructor for this type
        let constructorName = "\(typeName).__init"
        if let constructor = vm.environment.getGlobal(constructorName) {
            let result = try? vm.invokeValue(constructor, args: arguments)
            if case .instance(let ref) = result { return ref }
        }
        // Try memberwise init
        if let typeInfo = vm.currentProgram?.typeTable.first(where: { $0.name == typeName }) {
            let instance = InstanceRef(typeName: typeName, kind: typeInfo.kind)
            for prop in typeInfo.properties where !prop.isComputed && !prop.isStatic {
                instance.setProperty(prop.name, .nil_)
            }
            return instance
        }
        return nil
    }

    #if canImport(SwiftUI)
    /// Create a native SwiftUI view from an interpreted view instance.
    public func makeView(from instance: InstanceRef) -> ViewStub {
        let id = ObjectIdentifier(instance)
        let store: LanternStateStore
        if let existing = stateStores[id] {
            store = existing
        } else {
            store = LanternStateStore()
            stateStores[id] = store
        }
        let builder = ViewDescriptorBuilder()
        lastViewDescriptorBuilder = builder
        // Forward descriptor updates to consumers
        builder.onTreeBuilt = { [weak self] descriptor in
            self?.onViewDescriptorUpdated?(descriptor)
        }
        return ViewStub(vm: vm, instance: instance, stateStore: store,
                         descriptorBuilder: builder,
                         appStorageKeys: compiler.allAppStorageMappings[instance.typeName] ?? [:])
    }

    /// The view descriptor tree from the last view body evaluation.
    /// Populated automatically during ViewStub body evaluation via the
    /// ViewDescriptorBuilder passed through SwiftUIContext.
    public var currentViewDescriptor: ViewDescriptor? {
        lastViewDescriptorBuilder?.rootDescriptor
    }

    /// Called by ViewStub after each body evaluation to notify that
    /// the descriptor tree has been updated. Set by LanternKit's SessionController.
    public var onViewDescriptorUpdated: ((ViewDescriptor?) -> Void)?

    /// Retained reference to the last descriptor builder used during view rendering.
    var lastViewDescriptorBuilder: ViewDescriptorBuilder?
    #endif
}
